export class PermissionConstants {
  public static readonly TITLE_LOCATION: string = '定位服务未授权';
  public static readonly CONTENT_LOCATION: string = '您的定位服务未开启，开启定位功能才可以使用定位功能';
  public static readonly TITLE_MICROPHONE: string = '麦克风权限使用说明';
  public static readonly CONTENT_MICROPHONE: string =
    '天虹需要获取您的麦克风权限，以便您能正常使用语音功能等服务。拒绝或取消授权不影响使用其他服务';
  public static readonly TITLE_CAMERA: string = '相机权限使用说明';
  public static readonly CONTENT_CAMERA: string =
    '天虹需要申请摄像头拍摄权限，以便您能正常使用摄像头进行拍摄预览。拒绝或取消授权不影响使用其他服务';
}
